name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release docs
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '~1.15'
    - name: Build docs
      run: make build.public
      env:
        HUGO_BASE_URL: https://thethingsstack.io/
        HUGO_GOOGLEANALYTICS: ${{ secrets.HUGO_GOOGLEANALYTICS }}
        HUGO_PARAMS_FEEDBACK_CAMPAIGN: ${{ secrets.HUGO_PARAMS_FEEDBACK_CAMPAIGN }}
        HUGO_PARAMS_FEEDBACK_ENABLED: true
        HUGO_PARAMS_INTERCOM_APPID: ${{ secrets.HUGO_PARAMS_INTERCOM_APPID }}
        HUGO_PARAMS_INTERCOM_ENABLED: true
        HUGO_PARAMS_SEARCH_APIKEY: ${{ secrets.HUGO_PARAMS_SEARCH_APIKEY }}
        HUGO_PARAMS_SEARCH_ENABLED: true
        HUGO_PARAMS_SEARCH_INDEX: thethingsstack
    - name: Deploy documentation to Github pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc/public
